select * from USER_tables;
select * from members
insert into members values('aa@aa.aa','aaa','aaa',0)
delete from members

CREATE TABLE MEMBERS (
	ID VARCHAR2(100) PRIMARY KEY,
	PW VARCHAR2(100),
	NICK VARCHAR2(100) UNIQUE,
	BALANCE NUMBER(10)
)
SELECT * 
		FROM (SELECT ROWNUM AS RNUM, product.* FROM product ORDER BY seq)
  		 WHERE RNUM >= 11 AND ROWNUM <= 6;
select * from product order by seq
CREATE TABLE PRODUCT (
	SEQ NUMBER(10) PRIMARY KEY,
	MODEL VARCHAR2(100) UNIQUE,
	CPU VARCHAR2(100),
	GRAPHIC VARCHAR2(100),
    PRICE NUMBER(10),
    DETAIL VARCHAR2(1000)
)
select * from product 
DROP TABLE PRODUCT

CREATE TABLE REVIEW (
	SEQ NUMBER(10) PRIMARY KEY,
	MODEL VARCHAR2(100),
	R_DATE DATE DEFAULT SYSDATE,
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(1000),
	RATING NUMBER(3)
)

create sequence review_seq
	start with 1
	minvalue 1
	nocycle
	nocache
	noorder

CREATE TABLE BOARD (
	SEQ NUMBER(10) PRIMARY KEY,
	ID VARCHAR2(100),
	NICK VARCHAR2(100),
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(1000),
	B_DATE DATE DEFAULT SYSDATE,
	FOREIGN KEY (ID) REFERENCES MEMBERS (ID),
	FOREIGN KEY (NICK) REFERENCES MEMBERS (NICK)
)

CREATE TABLE REPLY (
	SEQ NUMBER(10) PRIMARY KEY,
	B_SEQ NUMBER(10),
	ID VARCHAR2(100),
	NICK VARCHAR2(100),
	CONTENT VARCHAR2(1000),
	R_DATE DATE DEFAULT SYSDATE,
	FOREIGN KEY (B_SEQ) REFERENCES BOARD (SEQ),
	FOREIGN KEY (ID) REFERENCES MEMBERS (ID),
	FOREIGN KEY (NICK) REFERENCES MEMBERS (NICK)
)


CREATE TABLE SHOP_BASKET (
	SEQ NUMBER(10) PRIMARY KEY,
	MODEL VARCHAR2(100),
	CLASSIFICATION NUMBER(1),
	ID VARCHAR2(100),
	P_SEQ NUMBER(10),
	S_DATE DATE DEFAULT SYSDATE,
	FOREIGN KEY (ID) REFERENCES MEMBERS (ID),
	FOREIGN KEY (P_SEQ) REFERENCES PRODUCT (SEQ)
)
create 
DROP TABLE SHOP_BASKET

