select * from USER_tables;
select * from members
insert into members values('aa@aa.aa','aaa','aaa',0)
delete from members

CREATE TABLE MEMBERS (
	ID VARCHAR2(100) PRIMARY KEY,
	PW VARCHAR2(100),
	NICK VARCHAR2(100) UNIQUE,
	BALANCE NUMBER(10)
)
SELECT * 
		FROM (SELECT ROWNUM AS RNUM, product.* FROM product ORDER BY seq)
  		 WHERE RNUM >= 11 AND ROWNUM <= 6;
select * from product order by seq
CREATE TABLE PRODUCT (
	SEQ NUMBER(10) PRIMARY KEY,
	MODEL VARCHAR2(100) UNIQUE,
	CPU VARCHAR2(100),
	GRAPHIC VARCHAR2(100),
    PRICE NUMBER(10),
    DETAIL VARCHAR2(1000)
)
select * from product 
DROP TABLE PRODUCT

CREATE TABLE REVIEW (
	SEQ NUMBER(10) PRIMARY KEY,
	MODEL VARCHAR2(100),
	R_DATE DATE DEFAULT SYSDATE,
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(1000),
	RATING NUMBER(3)
)

create sequence review_seq
	start with 1
	minvalue 1
	nocycle
	nocache
	noorder

CREATE TABLE BOARD (
	SEQ NUMBER(10) PRIMARY KEY,
	ID VARCHAR2(100),
	NICK VARCHAR2(100),
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(1000),
	B_DATE DATE DEFAULT SYSDATE,
	FOREIGN KEY (ID) REFERENCES MEMBERS (ID),
	FOREIGN KEY (NICK) REFERENCES MEMBERS (NICK)
)

select*from BOARD

CREATE TABLE REPLY (
	SEQ NUMBER(10) PRIMARY KEY,
	B_SEQ NUMBER(10),
	ID VARCHAR2(100),
	NICK VARCHAR2(100),
	CONTENT VARCHAR2(1000),
	R_DATE DATE DEFAULT SYSDATE,
	FOREIGN KEY (B_SEQ) REFERENCES BOARD (SEQ),
	FOREIGN KEY (ID) REFERENCES MEMBERS (ID),
	FOREIGN KEY (NICK) REFERENCES MEMBERS (NICK)
)


CREATE TABLE SHOP_BASKET (
	SEQ NUMBER(10) PRIMARY KEY,
	MODEL VARCHAR2(100),
	CLASSIFICATION NUMBER(1),
	ID VARCHAR2(100),
	P_SEQ NUMBER(10),
	S_DATE DATE DEFAULT SYSDATE,
	FOREIGN KEY (ID) REFERENCES MEMBERS (ID),
	FOREIGN KEY (P_SEQ) REFERENCES PRODUCT (SEQ)
)
select * from SHOP_BASKET
DROP TABLE SHOP_BASKET
create sequence basket_seq
	increment by 1
	start with 1

select distinct model from shop_basket where id='qq@qq.qq'

SELECT * 
		FROM (SELECT ROWNUM AS RNUM, product.* FROM product ORDER BY seq)
  		 WHERE seq >= 10 AND ROWNUM <=6
create sequence board_seq
start with 1
insert into board values(board_seq.nextval, 'qq@qq.qq', 'qqq','제목t54646est','내용56165ㅇㅇㅇㅇ', sysdate, '1', null)
select * from board


select * from members











-- CPUSCORE, GPUSCORE �� �߰��ϱ� ���� ������ �߰�
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2377, 'M1 7 core', 16159);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2378, 'M1 MAX 32 core', 72116);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2379, 'M1 PRO 16 core', 10352);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2380, 'M2 10 core', 24880);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2381, 'M2 8 core', 21009);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2382, 'M2 Max 30core', 19980);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2383, 'M2 Max 38core', 25103);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2384, 'M2 Pro 16core', 11224);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2385, 'M2 Pro 19core', 12968);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2386, 'Radeon 610M', 17177);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2387, 'Radeon 660M', 19921);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2388, 'Arc A350M', 3494);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2389, 'Adreno', 1405);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2390, 'Radeon Ryzen 3 PRO 7330U', 2149);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2391, 'N5100', 850);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2392, 'i5-11500', 950);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2393, 'i5-1155G7', 4500);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2394, 'i5-6200', 1100);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2395, 'i7-1165G7', 4500);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2396, 'i7-1265U', 4500);
INSERT INTO GPUBENCHMARK (SEQ, GPUNAME, SCORE)
VALUES (2397, 'Arc A370M', 4255);
commit;


CREATE TABLE PRODUCT_COPY AS
SELECT * FROM PRODUCT WHERE 1<>1;
CREATE TABLE PRODUCT_GPU AS
SELECT * FROM PRODUCT_COPY WHERE 1<>1;

SELECT * FROM PRODUCT_GPU;

ALTER TABLE PRODUCT_COPY
    ADD GPUSCORE NUMBER(8);

select * FROM PRODUCT WHERE CPU LIKE 'DDR%';
select * FROM PRODUCT WHERE CPU LIKE '__';
select * FROM PRODUCT WHERE CPU LIKE '%�ھ�';
select * FROM PRODUCT WHERE CPU LIKE '%Core';
select * FROM PRODUCT WHERE CPU LIKE '%00U';
UPDATE PRODUCT SET CPU = REGEXP_REPLACE(CPU, '\(.*\)', '');
UPDATE PRODUCT SET GRAPHIC = REPLACE(GRAPHIC, '�󵥿�', 'Radeon');
UPDATE PRODUCT SET CPU = LTRIM(CPU, 'AMD');
UPDATE PRODUCT SET CPU = LTRIM(CPU, 'Apple');
UPDATE PRODUCT SET CPU = TRIM(CPU);

-- CPU ��ġ��ũ�� JOIN
INSERT INTO PRODUCT_COPY (SEQ, MODEL, CPU, GRAPHIC, PRICE, DETAIL, SCORE)
    SELECT distinct p.SEQ, p.MODEL, p.CPU, p.GRAPHIC, p.PRICE, p.DETAIL, c.SCORE
        FROM PRODUCT p, CPUBENCHMARK c
        WHERE INSTR(c.cpuname, p.cpu) > 0;

-- GPU ��ġ��ũ�� JOIN
INSERT INTO PRODUCT_GPU (SEQ, MODEL, CPU, GRAPHIC, PRICE, DETAIL, SCORE, GPUSCORE)
    SELECT distinct p.SEQ, p.MODEL, p.CPU, p.GRAPHIC, p.PRICE, p.DETAIL, p.SCORE, g.SCORE
        FROM PRODUCT_COPY p, GPUBENCHMARK g
        WHERE INSTR(g.gpuname, p.graphic) > 0;

alter table product_copy add inout varchar2(15);

UPDATE "CAMPUS_C_230315_3"."PRODUCT_COPY" SET INOUT = '����׷���' WHERE INSTR(DETAIL, '����׷���') > 0;
UPDATE "CAMPUS_C_230315_3"."PRODUCT_COPY" SET INOUT = '����׷���' WHERE INSTR(DETAIL, '����׷���') > 0;
UPDATE "CAMPUS_C_230315_3"."PRODUCT_COPY" SET INOUT = '����׷���' WHERE INSTR(DETAIL, '����׷���') = 0 AND INSTR(DETAIL, '����׷���') = 0;
UPDATE "CAMPUS_C_230315_3"."PRODUCT_COPY" SET GPUSCORE = (SELECT g.SCORE FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.gpuname, p.graphic) > 0);
UPDATE "CAMPUS_C_230315_3"."PRODUCT_COPY" SET GRAPHIC = CASE WHEN INSTR(GRAPHIC, 'GTX') > 0 OR INSTR(GRAPHIC, 'RTX') > 0 THEN SUBSTR(GRAPHIC, 1, 3) || ' ' || SUBSTR(GRAPHIC, 4) END
WHERE INSTR(GRAPHIC, 'GTX') > 0 OR INSTR(GRAPHIC, 'RTX') > 0;

--TRUNCATE TABLE GPUBENCHMARK;
-- Semantic �ߺ� ����
-- 'Laptop GPU'�� ������ GPU ���
SELECT p.model, p.graphic, g.SCORE, g.GPUNAME FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND INSTR(g.gpuname, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18;

-- 'Laptop GPU'�� ������ GPU ���
SELECT p.model, p.graphic, g.SCORE, g.GPUNAME FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND INSTR(g.gpuname, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18;

-- 'Ti Laptop GPU'�� ������ GPU ���
SELECT p.model, p.graphic, g.SCORE, g.GPUNAME FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21;

-- 'Ti'�� ������ GPU ���
SELECT p.model, p.graphic, g.SCORE, g.GPUNAME FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2;

-- �� �´� ���
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1;

-- Iris Xe
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND p.INOUT = '����׷���' AND p.graphic = 'Iris Xe'
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1;

-- ����׷����ε� GPUBENCHMARK���� ��ȸ �ȵǴ°�
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE INSTR(g.GPUNAME, p.GRAPHIC) = 0;
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND p.INOUT = '����׷���';
SELECT distinct p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.GRAPHIC = 'Iris Xe';

SELECT * FROM PRODUCT_COPY WHERE INSTR(GRAPHIC, 'RTX') = 0 AND INSTR(GRAPHIC, 'GTX') = 0;
SELECT * FROM PRODUCT_COPY WHERE INSTR(GRAPHIC, 'RTX') > 0 OR INSTR(GRAPHIC, 'GTX') > 0;

-- GTX�� RTX�� �����ϴ� �� // �ߺ� ���Ŵ� �ȵ�
SELECT * FROM PRODUCT_COPY WHERE INSTR(GRAPHIC, 'RTX') > 0 OR INSTR(GRAPHIC, 'GTX') > 0;

UPDATE product_copy set graphic = REPLACE(GRAPHIC, 'UHD', 'UHD Graphics') WHERE INSTR(GRAPHIC, 'UHD Graphics') = 0;
UPDATE product_copy set graphic = CPU || ' with ' || GRAPHIC WHERE graphic = 'Radeon Graphics';
UPDATE product_copy set graphic = 'Intel HD 3000' WHERE graphic = 'HD 3000';
UPDATE product_copy set graphic = 'Intel HD Graphics 620' WHERE graphic = 'HD Graphics';
commit;
rollback;

-- RTX, GTX �� ��� ���� ����
--SELECT * FROM PRODUCT_COPY WHERE INSTR(GRAPHIC, 'RTX') > 0 OR INSTR(GRAPHIC, 'GTX') > 0
--MINUS
--SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
--AND INSTR(g.gpuname, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18
--MINUS
--SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
--AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21
--MINUS
--SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
--AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2
--MINUS
--SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
--AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1;

-- ��� ���� ����
SELECT * FROM PRODUCT_COPY
MINUS
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND INSTR(g.gpuname, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18 -- 1. Laptop GPU�� ����
MINUS
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21 -- 2. Ti Laptop GPU�� ����
MINUS
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2 -- 3. Ti�� ����
MINUS
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1 -- 4. �ش� GPU �̸����� ����
MINUS
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1 -- 5. Iris Xe�� ����
MINUS
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND (p.GRAPHIC = 'Arc A350M' OR p.GRAPHIC = 'Arc A370M') -- 6. Arc A350M, Arc A370M
MINUS
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics'
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1 -- 7. UHD Graphics
MINUS
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(p.graphic, 'UHD Graphics') > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1 -- 8. UHD Graphics 2
MINUS
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(p.GRAPHIC, 'Radeon') > 0
AND INSTR(g.GPUNAME, p.CPU) > 0 AND LENGTH(g.GPUNAME) <= 20 AND INSTR(g.GPUNAME, 'with Radeon Graphics') = 0 -- 9. Ryzen CPU ����
MINUS
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND g.GPUNAME = p.GRAPHIC -- 10. GPU �Ȱ���
MINUS
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.gpuname, p.graphic) > 0
AND (INSTR(g.gpuname, 'Ryzen') > 0 OR INSTR(g.gpuname, 'Silver') > 0) -- 11. Ryzen�̳� Silver ����
MINUS
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND g.gpuname = p.cpu OR p.CPU = 'i7-1195G7'; -- 12. CPU �Ȱ���

commit;

select * from v$version;


-- ������ �ڵ�!
-- 1. Laptop GPU�� ������ GPU // 763
UPDATE PRODUCT_COPY pc
SET GPUSCORE =
    (select score from (SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18)b
WHERE pc.seq = b.seq)
where seq in (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18);

-- 2. Ti Laptop GPU�� ������ GPU // 272
UPDATE PRODUCT_COPY pc
SET GPUSCORE =
    (select score from (
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18) b
WHERE pc.seq = b.seq)

WHERE SEQ IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21)
AND SEQ NOT IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18);

-- 3. Ti�� ������ GPU // 158
UPDATE PRODUCT_COPY pc
SET GPUSCORE =
    (SELECT SCORE FROM (
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2)
OR (INSTR(p.graphic, 'Ti') > 0 AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18) b
WHERE pc.seq = b.seq)

WHERE SEQ IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2)
OR (INSTR(p.graphic, 'Ti') > 0 AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1))
AND SEQ NOT IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21));

SELECT g.score, p.seq, p.graphic FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1;

SELECT p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1;

SELECT distinct p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1;

-- 4. �ش� GPU �̸����� ���� // 164
UPDATE PRODUCT_COPY pc
SET GPUSCORE =
    (SELECT SCORE FROM (
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18) b
WHERE pc.seq = b.seq)

WHERE SEQ IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
AND SEQ NOT IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2)
);

-- 5. Iris Xe�� ���� // 280
UPDATE PRODUCT_COPY pc
SET GPUSCORE =
    (SELECT SCORE FROM (
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18) b
WHERE pc.seq = b.seq)

WHERE SEQ IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)

AND SEQ NOT IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
);

SELECT g.score, p.seq, p.graphic FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE INSTR (g.gpuname, p.graphic) > 0 AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M');

---- 6. Arc A350M, Arc A370M // 18
--UPDATE PRODUCT_COPY pc
--SET GPUSCORE =
--    (SELECT SCORE FROM (
--SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE INSTR (g.gpuname, p.graphic) > 0 AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M')
--MINUS
--SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
--AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
--MINUS
--SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
--AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
--MINUS
--SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
--WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2
--MINUS
--SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
--WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21
--MINUS
--SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
--WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18) b
--WHERE pc.seq = b.seq)
--
--WHERE SEQ IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
--WHERE INSTR (g.gpuname, p.graphic) > 0 AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M'))
--
--AND SEQ NOT IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
--WHERE (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18)
--OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21)
--OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2)
--OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
--OR (p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
--);

-- 7. UHD Graphics // 70
UPDATE PRODUCT_COPY pc
SET GPUSCORE =
    (SELECT SCORE FROM (
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics'
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.graphic = g.gpuname AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M')
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18) b
WHERE pc.seq = b.seq)

WHERE SEQ IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics'
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)

AND SEQ NOT IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.graphic = g.gpuname AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M'))
);

-- 8. UHD Graphics 2 // 6
UPDATE PRODUCT_COPY pc
SET GPUSCORE =
    (SELECT SCORE FROM (
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(p.graphic, 'UHD Graphics') > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics'
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.graphic = g.gpuname AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M')
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18) b
WHERE pc.seq = b.seq)

WHERE SEQ IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(p.graphic, 'UHD Graphics') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)

AND SEQ NOT IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.graphic = g.gpuname AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M'))
OR (p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics' AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
);

-- 9. Ryzen CPU ���� // 18
UPDATE PRODUCT_COPY pc
SET GPUSCORE =
    (SELECT SCORE FROM (
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(p.GRAPHIC, 'Radeon') = 1 AND INSTR(g.GPUNAME, p.CPU) > 0 AND LENGTH(g.GPUNAME) <= 19
AND INSTR(g.GPUNAME, 'with Radeon Graphics') = 0
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(p.graphic, 'UHD Graphics') > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics'
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.graphic = g.gpuname AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M')
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18) b
WHERE pc.seq = b.seq)

WHERE SEQ IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(p.GRAPHIC, 'Radeon') = 1 AND INSTR(g.GPUNAME, p.CPU) > 0 AND LENGTH(g.GPUNAME) <= 19 AND INSTR(g.GPUNAME, 'with Radeon Graphics') = 0)

AND SEQ NOT IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.graphic = g.gpuname AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M'))
OR (p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics' AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.INOUT = '����׷���' AND INSTR(p.graphic, 'UHD Graphics') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
);


-- 10. GPU �Ȱ��� // 89
UPDATE PRODUCT_COPY pc
SET GPUSCORE =
    (SELECT SCORE FROM (
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND g.GPUNAME = p.GRAPHIC
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(p.GRAPHIC, 'Radeon') = 1 AND INSTR(g.GPUNAME, p.CPU) > 0 AND LENGTH(g.GPUNAME) <= 19
AND INSTR(g.GPUNAME, 'with Radeon Graphics') = 0
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(p.graphic, 'UHD Graphics') > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics'
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.graphic = g.gpuname AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M')
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18) b
WHERE pc.seq = b.seq)

WHERE SEQ IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND g.GPUNAME = p.GRAPHIC)

AND SEQ NOT IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.graphic = g.gpuname AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M'))
OR (p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics' AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.INOUT = '����׷���' AND INSTR(p.graphic, 'UHD Graphics') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.INOUT = '����׷���' AND INSTR(p.GRAPHIC, 'Radeon') = 1 AND INSTR(g.GPUNAME, p.CPU) > 0 AND LENGTH(g.GPUNAME) <= 19 AND INSTR(g.GPUNAME, 'with Radeon Graphics') = 0)
);

-- 11. Ryzen, Silver ���� // 72
UPDATE PRODUCT_COPY pc
SET GPUSCORE =
    (SELECT SCORE FROM (
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.gpuname, p.graphic) > 0
AND (INSTR(g.gpuname, 'Ryzen') > 0 OR INSTR(g.gpuname, 'Silver') > 0)
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND g.GPUNAME = p.GRAPHIC
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(p.GRAPHIC, 'Radeon') = 1 AND INSTR(g.GPUNAME, p.CPU) > 0 AND LENGTH(g.GPUNAME) <= 19
AND INSTR(g.GPUNAME, 'with Radeon Graphics') = 0
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(p.graphic, 'UHD Graphics') > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics'
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.graphic = g.gpuname AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M')
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18) b
WHERE pc.seq = b.seq)

WHERE SEQ IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.gpuname, p.graphic) > 0
AND (INSTR(g.gpuname, 'Ryzen') > 0 OR INSTR(g.gpuname, 'Silver') > 0))

AND SEQ NOT IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.graphic = g.gpuname AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M'))
OR (p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics' AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.INOUT = '����׷���' AND INSTR(p.graphic, 'UHD Graphics') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.INOUT = '����׷���' AND INSTR(p.GRAPHIC, 'Radeon') = 1 AND INSTR(g.GPUNAME, p.CPU) > 0 AND LENGTH(g.GPUNAME) <= 19 AND INSTR(g.GPUNAME, 'with Radeon Graphics') = 0)
OR (p.INOUT = '����׷���' AND g.GPUNAME = p.GRAPHIC)
);

-- 12. CPU �Ȱ��� // 1
UPDATE PRODUCT_COPY pc
SET GPUSCORE =
    (SELECT SCORE FROM (
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND g.gpuname = p.cpu
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.gpuname, p.graphic) > 0
AND (INSTR(g.gpuname, 'Ryzen') > 0 OR INSTR(g.gpuname, 'Silver') > 0)
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND g.GPUNAME = p.GRAPHIC
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(p.GRAPHIC, 'Radeon') = 1 AND INSTR(g.GPUNAME, p.CPU) > 0 AND LENGTH(g.GPUNAME) <= 19
AND INSTR(g.GPUNAME, 'with Radeon Graphics') = 0
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(p.graphic, 'UHD Graphics') > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics'
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.graphic = g.gpuname AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M')
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21
MINUS
SELECT g.score, p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18) b
WHERE pc.seq = b.seq)

WHERE SEQ IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE p.INOUT = '����׷���' AND g.gpuname = p.cpu)

AND SEQ NOT IN (SELECT p.seq from gpubenchmark g, PRODUCT_COPY P
WHERE (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.gpuname, 'Ti') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)+2)
OR (p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.GRAPHIC = 'Iris Xe' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.graphic = g.gpuname AND (p.graphic = 'Arc A350M' or p.graphic = 'Arc A370M'))
OR (p.INOUT = '����׷���' AND p.GRAPHIC = 'UHD Graphics' AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.INOUT = '����׷���' AND INSTR(p.graphic, 'UHD Graphics') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+LENGTH(p.GRAPHIC)-1)
OR (p.INOUT = '����׷���' AND INSTR(p.GRAPHIC, 'Radeon') = 1 AND INSTR(g.GPUNAME, p.CPU) > 0 AND LENGTH(g.GPUNAME) <= 19 AND INSTR(g.GPUNAME, 'with Radeon Graphics') = 0)
OR (p.INOUT = '����׷���' AND g.GPUNAME = p.GRAPHIC)
OR (p.INOUT = '����׷���' AND INSTR(g.gpuname, p.graphic) > 0 AND (INSTR(g.gpuname, 'Ryzen') > 0 OR INSTR(g.gpuname, 'Silver') > 0))
);

rollback;

SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND INSTR(g.gpuname, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18;

SELECT DISTINCT g.SCORE FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE INSTR(g.gpuname, p.graphic) > 0 AND (INSTR(p.graphic, 'GTX') > 0 OR INSTR(p.graphic, 'RTX') > 0);
SELECT graphic FROM product_copy where (instr(graphic, 'RTX') > 0 OR instr(graphic, 'GTX') > 0); -- 1232
SELECT g.score FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE INSTR(g.gpuname, p.graphic) > 0 AND (INSTR(p.graphic, 'GTX') > 0 OR INSTR(p.graphic, 'RTX') > 0);

SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND INSTR(g.gpuname, 'Ti Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+21;

SELECT p.*, g.gpuname FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.gpuname, p.cpu) > 0
AND (INSTR(g.gpuname, 'Ryzen') > 0 OR INSTR(g.gpuname, 'Silver') > 0);
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND g.GPUNAME = p.GRAPHIC;
SELECT p.* FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND g.gpuname = p.cpu;

-- 'Laptop GPU'�� ������ GPU ���
SELECT distinct g.gpuname FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND INSTR(g.gpuname, 'Laptop GPU') > 0 AND LENGTH(g.GPUNAME) = LENGTH(SUBSTR(g.GPUNAME, 1, INSTR(g.GPUNAME, p.GRAPHIC)))+18;

UPDATE PRODUCT_COPY SET GPUSCORE = (SELECT g.score FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(SUBSTR(g.gpuname, 1, INSTR(g.gpuname, p.graphic)+LENGTH(p.graphic)), p.graphic) > 0
AND LENGTH(g.gpuname) <= LENGTH(SUBSTR(g.gpuname, 1, INSTR(g.gpuname, p.graphic)+LENGTH(p.graphic))));

UPDATE PRODUCT_COPY p SET p.GPUSCORE = (SELECT g.score FROM GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(SUBSTR(g.gpuname, 1, INSTR(g.gpuname, p.graphic)+LENGTH(p.graphic)), p.graphic) > 0
AND LENGTH(g.gpuname) <= LENGTH(SUBSTR(g.gpuname, 1, INSTR(g.gpuname, p.graphic)+LENGTH(p.graphic))));

UPDATE PRODUCT_COPY p SET p.GPUSCORE = (SELECT g.score FROM GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND p.GPUSCORE IS NULL AND INSTR(p.GRAPHIC, 'RTX') > 0 OR INSTR(p.GRAPHIC, 'GTX') > 0
AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0);
UPDATE PRODUCT_COPY SET GPUSCORE = 21408 WHERE GRAPHIC = 'RTX 4070';

-- �ʱ�ȭ
UPDATE PRODUCT_COPY SET GPUSCORE = NULL;

UPDATE PRODUCT_COPY p SET p.GPUSCORE = (SELECT g.SCORE FROM GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND p.GPUSCORE IS NULL AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
AND INSTR(g.GPUNAME, 'Laptop GPU') > 0);

SELECT * FROM PRODUCT_COPY WHERE INSTR(DETAIL, CPU) = 0
MINUS
SELECT * FROM PRODUCT_COPY WHERE (INSTR(CPU, 'M1') > 0 OR INSTR(CPU, 'M2') > 0);

SELECT g.score FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND INSTR(SUBSTR(g.gpuname, 1, INSTR(g.gpuname, p.graphic)+LENGTH(p.graphic)), p.graphic) > 0
AND LENGTH(g.gpuname) <= LENGTH(SUBSTR(g.gpuname, 1, INSTR(g.gpuname, p.graphic)+LENGTH(p.graphic)));

SELECT * FROM PRODUCT_COPY WHERE GPUSCORE IS NULL AND INOUT = '����׷���';

SELECT p.MODEL, p.GRAPHIC, g.SCORE FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE (INSTR(p.GRAPHIC, 'RTX') > 0 OR INSTR(p.GRAPHIC, 'GTX') > 0) AND p.GPUSCORE IS NULL AND INSTR(g.GPUNAME, p.GRAPHIC) > 0
MINUS
SELECT p.MODEL, p.GRAPHIC, g.score FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.INOUT = '����׷���' AND p.GPUSCORE IS NULL AND (INSTR(p.GRAPHIC, 'RTX') > 0 OR INSTR(p.GRAPHIC, 'GTX') > 0)
AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0;

SELECT p.*, g.score FROM PRODUCT_COPY p, GPUBENCHMARK g WHERE p.GPUSCORE IS NULL AND INSTR(g.GPUNAME, p.GRAPHIC) > 0 AND INSTR(g.GPUNAME, 'Laptop GPU') > 0;

-- �����Ͽ��� GPU ��ã�����°� ��ȸ // ����
SELECT * FROM PRODUCT_COPY WHERE INSTR(DETAIL, GRAPHIC) = 0 AND INSTR(GRAPHIC, 'RTX') = 0 AND INSTR(GRAPHIC, 'GTX') = 0;

SELECT CPU, COUNT(CPU)
    FROM PRODUCT_COPY
    GROUP BY CPU
    ORDER BY COUNT(CPU) DESC;

SELECT SUBSTR(GRAPHIC, 1, 3) || ' ' || SUBSTR(GRAPHIC, 4) FROM PRODUCT_COPY WHERE INSTR(GRAPHIC, 'GTX') > 0 OR INSTR(GRAPHIC, 'RTX') > 0;
SELECT * FROM PRODUCT_COPY WHERE INSTR(GRAPHIC, 'GTX') > 0;
SELECT * FROM PRODUCT_COPY WHERE INSTR(GRAPHIC, 'RTX') > 0;
SELECT COUNT(GRAPHIC) FROM PRODUCT_COPY WHERE INSTR(GRAPHIC, 'GTX') > 0 OR INSTR(GRAPHIC, 'RTX') > 0;
SELECT COUNT(GRAPHIC) FROM PRODUCT_COPY WHERE INSTR(GRAPHIC, 'GTX') > 0;
SELECT COUNT(GRAPHIC) FROM PRODUCT_COPY WHERE INSTR(GRAPHIC, 'RTX') > 0;
SELECT COUNT(GRAPHIC) FROM PRODUCT_COPY WHERE INSTR(GRAPHIC, 'GTX') = 0 AND INSTR(GRAPHIC, 'RTX') = 0;
SELECT COUNT(GRAPHIC) FROM PRODUCT_COPY WHERE INOUT = '����׷���';

--SELECT SUBSTR('HelloWorld', 1, 5) || ' ' || SUBSTR('HelloWorld', 6) AS modified_string FROM dual;

--truncate table product_gpu;

SELECT CPU, COUNT(CPU)
    FROM PRODUCT_COPY
    GROUP BY CPU
    ORDER BY COUNT(CPU) DESC;

select score from product_copy order by score desc;

SELECT MODEL, COUNT(MODEL)
    FROM PRODUCT_COPY
    GROUP BY MODEL
    ORDER BY COUNT(MODEL) DESC;

select * from cpubenchmark;

select * from product_copy;